name: github-pr-labels
description: Retrieve the labels attached to a PR build and expose them via env vars or meta-data
author: https://github.com/blstrco
requirements:
  - curl
  - jq
configuration:
  definitions:
    token-from-object:
      type: object
      properties:
        env:
          type: string
        file:
          type: string
      oneOf:
        - required:
            - env
        - required:
            - file
      additionalProperties: false
    pull-request-from-id-object:
      type: object
      properties:
        pattern:
          type: [string, array]
        source:
          type: string
      required:
        - pattern
        - source
      additionalProperties: false
  properties:
    token-from:
      $ref: "#/definitions/token-from-object"
    publish-env-var:
      type: string
    publish-metadata-key:
      type: string
    pull-request-id-from:
      $ref: "#/definitions/pull-request-from-id-object"
  additionalProperties: false
